// Multi-language translation dictionary for Taiwan Big Two AI

export type Language = 'zh' | 'en';

export const TRANSLATIONS = {
  zh: {
    // Nav / Header
    brandName: '台灣大老二 AI',
    brandSub: 'Taiwan Big Two AI - 全台最強對戰平台',
    navFeatures: '特色亮點',
    navMsStore: '微軟商店',
    navChallenges: '殘局挑戰',
    navDemo: 'Demo',
    navLeaderboard: '排行榜',
    navAlgorithm: 'AI 角色',
    btnMsStoreDownload: '微軟商店下載',
    btnShareSite: '分享網站',
    btnPlayNowHeader: '立即開局',
    btnShareTooltip: '分享此網站給朋友',
    toastShareSuccess: '已複製分享連結！快傳給好友挑戰吧 🃏 (https://mesmerli.github.io/twbig2/)',

    // Hero
    heroSubtitle: '台味撲克 × 頂級 decision AI',
    heroTitlePart1: '極致流暢',
    heroTitlePart2: '台灣大老二 AI',
    heroDesc: '主打最深度的決策演算法與微秒級流暢出牌體驗。首創結合多元大模型 AI 牌風性格，賽後提供專屬 AI 評價反饋與互動問答，帶你體驗原汁原味卻智商爆棚的台灣大老二魅力！',
    statBadge1Val: '15',
    statBadge1Unit: 'ms',
    statBadge1Lbl: 'AI 毫秒決策延遲',
    statBadge2Val: '100',
    statBadge2Unit: '%',
    statBadge2Lbl: '台灣大老二規則覆蓋',
    statBadge3Val: 'LLM',
    statBadge3Unit: '',
    statBadge3Lbl: 'AI 賽後點評與問答',
    btnStartWebPlay: '開始線上試玩',
    btnMsStoreTrial: 'Microsoft Store 官方下載 (30天免費試用)',
    btnVisitGithub: '造訪 GitHub 專案',
    visualTitle: '極致流暢 AI 算力',
    visualDesc: '深度學習驅動的台灣味對手，隨時隨地，3秒開桌，告別等待。',

    // Features
    featuresTitle: '三大研發核心特色',
    featuresSub: '基於大語言模型（LLM）與 `mesmerli/taiwan-big-two-ai` 嚴謹決策架構，重塑傳統撲克智慧。',
    feat1Title: '多元人格研究架構',
    feat1Desc: '模擬人類的心理思維！核心內建多元人格 (Multi-Persona Architecture)，包含保守、激進、靈活與自適應等多種不同牌風與風險偏好的人工智慧對手，拒絕機械式出牌，博弈感十足。',
    feat2Title: '賽後 AI 點評與策略問答',
    feat2Desc: '對局結束後，由大語言模型（LLM）擔任專家裁判，對整場牌局的出牌時機、剩餘手牌與關鍵勝負決策進行深度復盤，並以對話問答方式一對一交流，幫您看清對手套路、快速精進牌技。',
    feat3Title: '嚴謹正宗台灣大老二規則',
    feat3Desc: '完美承襲「梅花 3 必須先行出牌」、「黑桃 2 最大」等台式傳統。支持單張、對子、以及順子、同花、葫蘆、四條（鐵支）、同花順等五張牌型組合，具備縝密的牌型檢驗與大小比對邏輯。',

    // Ms Store Section
    msCert: 'Microsoft Store 官方認證',
    msTitle: '取得 Windows 原生桌面版',
    msDesc: '除了網頁免安裝直接遊玩，您現在也可以至微軟商店取得 Windows 專屬客戶端！商店定價為美金 $9.99 Base Price，但提供完整的 30 天免費流暢試玩體驗。邀您即刻免費下載體驗！',
    msBenefit1: '支援離線對決、單機練習',
    msBenefit2: '30天完整免費試玩體驗',
    msBenefit3: '一鍵安裝，後台極速啟動',
    msBenefit4: '完美配適鍵盤與高保真畫面',
    msClientTitle: '台灣大老二 AI',
    msClientPricing: '定價 $9.99 美金 | 首月 30 天免費試玩',
    msClientBtn: '免費下載試玩 (30天)',
    msClientOS: '適用於 Windows 10/11 平台',

    // App.tsx Specific Microsoft Keys
    msStoreBannerTag: 'Microsoft Store 官方認證',
    msStoreBannerTitle: '取得 Windows 原生桌面版',
    msStoreBannerDesc: '除了網頁免安裝直接遊玩，您現在也可以至微軟商店取得 Windows 專屬客戶端！商店定價為美金 $9.99 Base Price，但提供完整的 30 天免費流暢試玩體驗。邀您即刻免費下載體驗！',
    msStoreBannerBullet1: '支援離線對決、單機練習',
    msStoreBannerBullet2: '30天完整免費試玩體驗',
    msStoreBannerBullet3: '一鍵安裝，後台極速啟動',
    msStoreBannerBullet4: '完美配適鍵盤與高保真畫面',
    msStoreTrialText: '定價 $9.99 美金 | 首月 30 天免費試玩',
    btnMsStoreTrialBanner: 'Microsoft Store 官方下載 (30天免費試用)',
    msStoreFooterText: '適用於 Windows 10/11 平台',

    // Daily Challenges
    challengeTitle: '🎯 每日挑戰：台灣大老二殘局特訓',
    challengeDesc: '今日已有上千位牌客嘗試挑戰。選定以下殘局，點擊「挑戰」即可一鍵部署戰局桌椅，成功破解即可斬獲頭銜與排行榜分數加成！',
    challengeRefresh: '⏰ 每日 00:00AM 全自動刷新',
    challengePoints: '🌟 積分 +150',
    btnChallengeSolve: '破解殘局 →',
    btnChallengeActive: '正在熱戰中',
    statusSolved: '已破局',
    statusUnsolved: '未破局',

    // App.tsx Specific Daily Challenges Keys
    challengesTitle: '🎯 每日挑戰：台灣大老二殘局特訓',
    challengesDesc: '今日已有上千位牌客嘗試挑戰。選定以下殘局，點擊「挑戰」即可一鍵部署戰局桌椅，成功破解即可斬獲頭銜與排行榜分數加成！',
    challengesAutoRefresh: '⏰ 每日 00:00AM 全自動刷新',
    challengesStatusCompleted: '已破局',
    challengesStatusPending: '未破局',
    challengesScore: '🌟 積分',
    challengesActionActive: '正在熱戰中',
    challengesActionStart: '破解殘局 →',

    challengesData: {
      challenge_1: {
        title: '黑桃二的驚天逆襲',
        description: '此時對方剩餘 2 張牌（已知含有梅花 K）。你的手上僅剩 3 張，包含壓底的【黑桃2】與【鑽石 4】、以及【紅心 Q】。輪到你出牌，如何打出完美結局贏得本局？',
      },
      challenge_2: {
        title: '梅花三的絕地反擊（新手局）',
        description: '桌面上無牌，輪到你開局。你手上有【梅花 3】、【黑桃 Q】、【紅心 2】。對手手上有【紅心 Q】與【鑽石 Q】。請打出包含梅花3的組合，並在對手防備下最終用紅心2奪得勝果。',
      },
      challenge_3: {
        title: '鐵支破壞狂（高手局）',
        description: '對方剩餘 5 張牌（暗示可能為順子或同花）。你手握【黑桃 A】與【紅心 A】一對，以及【梅花 2】。對手手牌強大，你必須精準卡位，利用對手過牌機會，引誘他拆牌，再以大牌一槌定音！',
      }
    },

    // Demo Room
    localGameTag: '台北大同戰局區 (自研模擬引擎版)',
    officialGameTag: '遠端官方獨立主機：連線運作中',
    demoHeadline: '🎴 立刻線上切磋：智慧對決桌面',
    demoSubDesc: '您可以切換遊玩「官網線上正式版」或體驗具備「每日殘局挑戰」的本地自研模擬桌！',
    puzzleModeActive: '⚡ 現正處於【{name}】殘局特訓模式',
    btnReturnToNormal: '切換回普通 AI 13張對戰',
    btnOfficialEdition: '🌐 官網線上正式版 IP 戰局',
    btnLocalEdition: '🎯 網頁試玩 & 每日殘局',
    embedWarning: '目前已完美為您在沙盒框架中安全嵌入台灣大老二開源項目官網！',
    embedNewTab: '不限制直接開新分頁全螢幕遊玩',

    // App.tsx Specific Demo Keys
    demoTitle: '🎴 立刻線上切磋：智慧對決桌面',
    demoSubtitle: '您可以切換遊玩「官網線上正式版」或體驗具備「每日殘局挑戰」的本地自研模擬桌！',
    demoActiveChallengePrefix: '⚡ 現正處於【',
    demoActiveChallengeSuffix: '】殘局特訓模式',
    demoSwitchNormalPlay: '切換回普通 AI 13張對戰',
    demoModeOfficial: '🌐 官網線上正式版 IP 戰局',
    demoModeLocal: '🎯 網頁試玩 & 每日殘局',
    demoStatusOfficial: '遠端官方獨立主機：連線運作中',
    demoStatusLocal: '台北大同戰局區 (自研模擬引擎版)',
    iframeSandboxNotice: '目前已完美為您在沙盒框架中安全嵌入台灣大老二開源項目官網！',
    iframeFullWidthBtn: '不限制直接開新分頁全螢幕遊玩',

    // Character Profile Customizer
    customizerHeadline: '自訂你的神級牌客屬性',
    lblNickname: '對決暱稱',
    lblPersonaTitle: '大專專屬牌客稱號',
    scoreSummary: '🏆 當前積分：{score}分',
    scoreSummarySub: '此積分將實時刷新你在全網玩家排行榜的位置，快試試更改名字吧！',
    btnApplyCustomizer: '確認修改、加入江湖！',
    defaultNickname: '萬華牌王阿強',
    defaultTitle: '東區大老二至尊',
    defaultLocalTitle: '萬華牌局一陣風',

    // App.tsx Specific Customizer Keys
    custTitle: '自訂你的神級牌客屬性',
    custLabelNickname: '對決暱稱',
    custPlaceholder: '請輸入對決暱稱',
    custLabelTitle: '大專專屬牌客稱號',
    custScoreText: '當前積分',
    custDescText: '此積分將實時刷新你在全網玩家排行榜的位置，快試試更改名字吧！',
    custConfirmBtn: '確認修改、加入江湖！',

    // Leaderboard
    leaderboardTitle: '🏆 台灣大老二・實時神級王牌排行榜',
    leaderboardDesc: '由全台真實玩家對抗記錄演算出。贏得更多殘局或戰局，即可提升排名！',
    leaderboardLiveBadge: '實時連接中',
    thRank: '排名',
    thName: '大老二名號',
    thTitle: '江湖稱號',
    thRecord: '戰績',
    thPoints: '排位精準積分',
    thMedals: '近期榮譽勳章',
    winText: '勝',
    gameText: '局',
    youLabel: '(你)',

    // App.tsx Specific Leaderboard Keys
    leaderboardStatus: '實時連接中',
    leaderboardThRank: '排名',
    leaderboardThName: '大老二名號',
    leaderboardThTitle: '江湖稱號',
    leaderboardThRecord: '戰績',
    leaderboardThScore: '排位精準積分',
    leaderboardThMedals: '近期榮譽勳章',

    // Algorithm & Tech
    techTag: '核心開源技術：大老二決策智慧',
    techTitle: '基於 taiwan-big-two-ai 演算法架構',
    techDesc: '本落地頁的 AI 出牌選擇演算法直接繼承了來自 mesmerli/taiwan-big-two-ai 的開源精神。針對台灣大老二多牌型組合的極限搜尋，實現了高精度推理。',
    techBullet1: '五張牌組合精準剪枝：自動優化順子、同花、葫蘆、鐵支的排序層級，確保五張能精準壓制。',
    techBullet2: '梅花 3 特殊開局保護：嚴格覆蓋台灣在地開局傳統（持有梅花三者必須將其包含在首波手牌中）。',
    techBullet3: '鐵支與同花順規則特判：覆蓋各類戰略情況下的主動權變動，AI 能判斷何時用鐵支一槌定局。',
    codeSnippetTitle: '📂 @utils/bigTwoRules.ts - 核心決策精簡邏輯',
    codeSnippetFooter: '🎉 欲獲取包含搜索樹、卷積神經網路預估牌勝率的完整代碼，請參照 GitHub 下載。',

    // App.tsx Specific Algorithm & Tech Keys
    techBadge: '核心開源技術：大老二決策智慧',
    techLi1: '五張牌組合精準剪枝：自動優化順子、同花、葫蘆、鐵支的排序層級，確保五張能精準壓制。',
    techLi2: '梅花 3 特殊開局保護：嚴格覆蓋台灣在地開局傳統（持有梅花三者必須將其包含在首波手牌中）。',
    techLi3: '鐵支與同花順規則特判：覆蓋各類戰略情況下的主動權變動，AI 能判斷何時用鐵支一槌定局。',
    techFooterNotice: '🎉 欲獲取包含搜索樹、卷積神經網路預估牌勝率的完整代碼，請參照 GitHub 下載。',

    // Footer
    footerCommunity: '台灣大老二 AI 連線社群',
    footerCommunityDesc: '本專案由開源愛好者與大老二迷合力打造，致敬台灣道地傳統棋牌。',
    footerContact: '聯絡信箱：',
    footerDlClient: '下載 Windows 客戶端：',
    footerCoreProject: '技術核心專案：',

    // App.tsx Specific Footer Keys
    footerTitle: '台灣大老二 AI 連線社群',
    footerDesc: '本專案由開源愛好者與大老二迷合力打造，致敬台灣道地傳統棋牌。',
    footerDownloadText: '下載 Windows 客戶端：',
    footerPlatformText: 'Microsoft Store 官方下載 (30天免費試用)',
    footerRepoText: '技術核心專案：',
    shareToastText: '已複製分享連結！快傳給好友挑戰吧 🃏',

    // BigTwoGame.tsx Translations
    gameSoundOn: '音樂音效：開',
    gameSoundOff: '音樂音效：關',
    game1v1Tag: '🤝 單挑局',
    gameTurnMyTurn: '💡 已輪到你出手！選擇符合牌型的組合，點擊「出牌」',
    gameTurnOppTurn: '⏳ 對手正在組織策略，靜靜等待下一輪...',
    gameBtnPlay: '🚀 出牌',
    gameBtnPass: '💨 過牌 (Pass)',
    gameBtnReset: '重選',
    gameLogHeader: '戰局即時日誌',
    gameEmptyLog: '無最新對戰記錄',
    gameMyProfile: '💡 我的桌邊屬性',
    gameProfileNickname: '目前暱稱',
    gameProfileTitle: '當前稱號',
    gameProfileTip: '透過獲勝或解答精選殘局，提升排位積分，將直接回傳至全網排行榜！',

    gameInitNormalLog: '💡 遊戲開局！由持有 [梅花 3] 的 [{name}] 先攻發行！',
    gameSpeechAiMaster: '哈哈，梅花三在我手，這盤主動權由我掌管！',
    gameSpeechHumanMaster: '看我起手神牌，準備受死吧！',
    gamePuzzleStartLog: '⚔️ [殘局挑戰開始]：{title}',
    gamePuzzleStartOppLabel: '📢 今日對抗：{desc}',
    gamePuzzleStartInfoLine: '💡 請謹慎出第一張牌，並想辦法在回合限制內擊敗守門員過關！',
    gamePuzzleStartHumanSpeech: '殘局已布好，看我如何一劍封喉！',
    gameSpeechSingleCard: '各位鄉親！只剩一張！聽牌啦！',
    gameLogPlayed: '🥊 [{name}] 出牌：[{type}] ({cardsDesc})',
    gameLogPassed: '💨 [{name}] 選擇 [過牌]！',
    gameLogCleared: '🔄 桌面上大家都過牌了，戰局重置！由 [{name}] 重新獲得主動出牌權！',
    gameResultTitleWin: '🏆 殘局破解成功！',
    gameResultTitleLose: '💀 破局失敗',
    gameResultBodyWin: '🎉 太神啦！你以完美的決策邏輯成功破解了本期殘局特訓！分數已為你加上！',
    gameResultBodyLose: '❌ 很遺憾，手牌數限制或落入對方守備套路，本次挑戰未能破局，再試一次吧！',
    gamePlayAgain: '再玩一局',
    gameResetSetup: '重整挑戰',
    gameReturnNormalMode: '回到一般模式',
    gameTitleWinNormal: '🏆 震撼全場！恭喜 [{name}] 牌數率先清空，獲得本局勝利 👑！',
    gameTitleLoseNormal: '💀 本局落幕！[{name}] 率領大局宣告完勝，再接再厲！',

    // Local Titles & Ai Opponent titles
    localTitles: [
      '西門町神釣手',
      '信義區彭于晏',
      '萬華牌局一陣風',
      '大安區包租公',
      '淡水河神算子',
      '逢甲林志玲',
      '高雄發哥',
      '三重老皮',
      '大奶微微愛好者',
      '竹科加班狂'
    ],
    opponent1Name: '東區大老二至尊',
    opponent2Name: '高雄發哥',
    opponent3Name: '三重老皮',
    opponentMysticName: '神秘牌客',
    oppTitle1: '老司機大師',
    oppTitle2: '夜市賭聖',
    oppTitle3: '萬華神算手',
    generalOpponentTag: '殘局挑戰者',
    generalExaminerTag: '殘局考驗官',

    // Character profiles keys
    charSectionTitle: 'AI 角色戰術指南',
    charSectionSubtitle: '洞悉傳統電腦與大語言模型 AI 的獨特個性與出牌邏輯，助您百戰百勝！',
    charTypeHeuristic: '基礎電腦玩家 (Traditional Heuristic AIs)',
    charTypeLlm: '進階大語言模型玩家 (LLM-Powered AIs)',
    charEngineTitle: '🔄 LLM 角色動態人格引擎 (Persona Engine)',
    charEngineDesc: 'LLM 角色每局會從以下四種戰術人格之中隨機挑選一個運作：',
    charEngine1Title: '防守之牆 (The Wall)',
    charEngine1Desc: '防守與卡牌優先。願拆大牌/對子阻截即將獲勝的對手。',
    charEngine2Title: '極速衝刺 (The Sprinter)',
    charEngine2Desc: '極速清空手牌。前期主打五張組合與高對子，不在乎防守。',
    charEngine3Title: '潛行獵人 (The Predator)',
    charEngine3Desc: '前期隱忍，保留大單牌與大對，後半局致命控牌回擊。',
    charEngine4Title: '狂暴戰士 (The Berserker, Ares聯動)',
    charEngine4Desc: '拒絕PASS！只要能壓就絕對強行出手，拿大牌強控主導權。',
    charAlexTitle: 'Alex — 平衡型 (Balanced)',
    charAlexDesc: '攻守兼備的穩健型棋手。依對手威脅程度動態調整出牌。',
    charAlexLead: '領牌偏好 / 出牌順序：防守時避出對子（五張 ➔ 單張 ➔ 最小單張）；一般時五張 ➔ 對子 ➔ 最小單張。',
    charBellaTitle: 'Bella — 防守型 (Defensive Pairs)',
    charBellaDesc: '保守防守。極好用對子掌控節奏，留高價值大單牌防禦。',
    charBellaLead: '領牌偏好 / 出牌順序：永遠最優先出最小對子，無對子出五張，完全無組合才出最小單張。',
    charChrisTitle: 'Chris — 進攻型 (Aggressive High)',
    charChrisDesc: '侵略進攻。以大壓小維持回合主導，狂丟大牌以快速脫身。',
    charChrisLead: '領牌偏好 / 出牌順序：優先打最大五張牌，無則打非2最大單牌強擄出牌權，2留作備用。',
    charDianaTitle: 'Diana — 智多星 (The Oracle)',
    charDianaDesc: '偏重戰術組合的建設與釋放。善用 J, Q, K 開闢發牌路徑。',
    charDianaTactics: '核心戰術：積極建立順子、對子等連串組合，奪取中期的控牌權與價值極大化。',
    charAresTitle: 'Ares — 戰神 (The God of War)',
    charAresDesc: '核心大牌掌控者。擅用中等牌（7, 8, 9）擾亂破壞對手牌型。',
    charAresTactics: '核心戰術：視 A, 2 為驚動性籌碼，後期爆發壓制；前中期多以干涉阻礙對手為主。',
  },
  en: {
    // Nav / Header
    brandName: 'Taiwan Big Two AI',
    brandSub: 'Taiwan Big Two AI - Ultimate Duel Platform',
    navFeatures: 'Features',
    navMsStore: 'MS Store',
    navChallenges: 'Puzzles',
    navDemo: 'Demo',
    navLeaderboard: 'Leaderboard',
    navAlgorithm: 'AI Profiles',
    btnMsStoreDownload: 'MS Store',
    btnShareSite: 'Share Site',
    btnPlayNowHeader: 'Play Now',
    btnShareTooltip: 'Share this website with friends',
    toastShareSuccess: 'Copied link! Share it with friends to challenge them! 🃏 (https://mesmerli.github.io/twbig2/)',

    // Hero
    heroSubtitle: 'Taiwan Style Poker × Elite Decision AI',
    heroTitlePart1: 'Butter Smooth',
    heroTitlePart2: 'Taiwan Big Two AI',
    heroDesc: 'Featuring deep-decision heuristic algorithms and microsecond card play. Pioneer of multiple-persona AI with exclusive post-game AI coaching and interactive Q&As, delivering an authentic yet brilliantly intellectual experience!',
    statBadge1Val: '15',
    statBadge1Unit: 'ms',
    statBadge1Lbl: 'AI Decision Latency',
    statBadge2Val: '100',
    statBadge2Unit: '%',
    statBadge2Lbl: 'Taiwan Rules Coverage',
    statBadge3Val: 'LLM',
    statBadge3Unit: '',
    statBadge3Lbl: 'Post-Game AI Reviews & Q&A',
    btnStartWebPlay: 'Start Web Play',
    btnMsStoreTrial: 'Microsoft Store Official Download (30-day Free Trial)',
    btnVisitGithub: 'Visit GitHub Repo',
    visualTitle: 'Extreme AI Power',
    visualDesc: 'Deep-learning driven Taiwanese opponents. Instantly start a table in 3 seconds anywhere, anytime.',

    // Features
    featuresTitle: 'Three Core R&D Highlights',
    featuresSub: 'Reimagining chess & cards wisdom based on Large Language Models (LLM) and the precise `mesmerli/taiwan-big-two-ai` framework.',
    feat1Title: 'Multi-Persona Engine',
    feat1Desc: 'Simulates human psychology! Built-in multi-persona opponent styles (conservative, aggressive, adaptive, etc.) with diverse risk thresholds for high stakes and exciting tactical poker play.',
    feat2Title: 'Post-Game AI Q&A Coach',
    feat2Desc: 'At finish, Large Language Models act as custom advisors, evaluating exact timing, cards left, and pivotal plays. Talk inside the Q&A window to quickly master professional meta strategies.',
    feat3Title: 'Authentic Taiwan Rules',
    feat3Desc: 'Fully honors traditions like "Club 3 must start" and "Spade 2 is largest". Accurate checks for single cards, pairs, and 5-card combos (straights, flushes, full houses, quads, straight flushes).',

    // Ms Store Section
    msCert: 'Microsoft Store Certified',
    msTitle: 'Get Native Windows App',
    msDesc: 'Along with immediate zero-setup web trial, acquire our high-performance Windows Client on MS Store. Normally priced at $9.99 Base price, but it comes with a complete 30-Day Free Trial! We invite you to download and experience it free now!',
    msBenefit1: 'Offline practice simulator',
    msBenefit2: 'Complete 30-day free trial',
    msBenefit3: 'Seamless background quick bootstrap',
    msBenefit4: 'Perfect keyboard binds & high fidelity v-sync',
    msClientTitle: 'Taiwan Big Two AI',
    msClientPricing: 'Base Price $9.99 USD | 30 Days Free Trial',
    msClientBtn: 'Download Free Trial (30d)',
    msClientOS: 'Compatible with Windows 10/11',

    // App.tsx Specific Microsoft Keys
    msStoreBannerTag: 'Microsoft Store Certified',
    msStoreBannerTitle: 'Get Native Windows App',
    msStoreBannerDesc: 'Along with immediate zero-setup web trial, acquire our high-performance Windows Client on MS Store. Normally priced at $9.99 Base price, but it comes with a complete 30-Day Free Trial! We invite you to download and experience it free now!',
    msStoreBannerBullet1: 'Offline practice simulator',
    msStoreBannerBullet2: 'Complete 30-day free trial',
    msStoreBannerBullet3: 'Seamless background quick bootstrap',
    msStoreBannerBullet4: 'Perfect keyboard binds & high fidelity v-sync',
    msStoreTrialText: 'Base Price $9.99 USD | 30 Days Free Trial',
    btnMsStoreTrialBanner: 'Download on Microsoft Store (30-day Free Trial)',
    msStoreFooterText: 'Compatible with Windows 10/11',

    // Daily Challenges
    challengeTitle: '🎯 Daily Challenge: End-Game Special Training',
    challengeDesc: 'Over thousands of players have attempted today\'s setup. Select any puzzle, click solve, and instantly deploy cards to capture honors and leaderboard points bonuses!',
    challengeRefresh: '⏰ Automatically refreshes at 00:00AM',
    challengePoints: '🌟 MMR Score +150',
    btnChallengeSolve: 'Crack Puzzle →',
    btnChallengeActive: 'Active Combat',
    statusSolved: 'Solved',
    statusUnsolved: 'Unsolved',

    // App.tsx Specific Daily Challenges Keys
    challengesTitle: '🎯 Daily Challenge: End-Game Special Training1',
    challengesDesc: 'Over thousands of players have attempted today\'s setup. Select any puzzle, click solve, and instantly deploy cards to capture honors and leaderboard points bonuses!',
    challengesAutoRefresh: '⏰ Automatically refreshes at 00:00AM',
    challengesStatusCompleted: 'Solved',
    challengesStatusPending: 'Unsolved',
    challengesScore: '🌟 Score',
    challengesActionActive: 'Active Combat',
    challengesActionStart: 'Crack Puzzle →',

    challengesData: {
      challenge_1: {
        title: '驚天大逆襲 (Spade Two\'s Comeback)',
        description: 'The opponent has 2 cards remaining (including Club K). You hold 3 cards: Spade 2 (largest), Heart Q, and Diamond 4. You lead. Solve the hand to win.',
      },
      challenge_2: {
        title: '絕地反擊 (Club Three\'s Revenge)',
        description: 'Empty table. You open the board. Your hand: Club 3, Spade Q, Heart 2. Opponent holds Heart Q and Diamond Q. Open correctly, bypass their defense, and dominate using Heart 2.',
      },
      challenge_3: {
        title: '鐵支破壞狂 (Four-of-a-Kind Disruptor)',
        description: 'Opponent holds 5 cards (hints a straight/flush combo). You hold Spades A & Hearts A pair, plus Club 2. Bait out their defensive play, force them to break their combos, and crush them!',
      }
    },

    // Demo Room
    localGameTag: 'Taipei Datong Arena (Web Simulator)',
    officialGameTag: 'Remote Pro Server: Live Connected',
    demoHeadline: '🎴 Play Now: Undergo Intelligence Duel',
    demoSubDesc: 'Instantly toggle between the "Official Online Pro Edition" or solve daily challenges on our local web sandbox.',
    puzzleModeActive: '⚡ Active Puzzle Mode: [{name}]',
    btnReturnToNormal: 'Change Back to Standard 13-Card AI',
    btnOfficialEdition: '🌐 Official Pro Online Edition',
    btnLocalEdition: '🎯 Web Sandbox & Daily Puzzles',
    embedWarning: 'Successfully initialized official project website securely in the isolated sandbox viewport!',
    embedNewTab: 'Open in new window for unrestricted full-screen play',

    // App.tsx Specific Demo Keys
    demoTitle: '🎴 Play Now: Undergo Intelligence Duel',
    demoSubtitle: 'Instantly toggle between the "Official Online Pro Edition" or solve daily challenges on our local web sandbox.',
    demoActiveChallengePrefix: '⚡ Active Puzzle Mode: [',
    demoActiveChallengeSuffix: ']',
    demoSwitchNormalPlay: 'Change Back to Standard 13-Card AI',
    demoModeOfficial: '🌐 Official Pro Online Edition',
    demoModeLocal: '🎯 Web Sandbox & Daily Puzzles',
    demoStatusOfficial: 'Remote Pro Server: Live Connected',
    demoStatusLocal: 'Taipei Datong Arena (Web Simulator)',
    iframeSandboxNotice: 'Successfully initialized official project website securely in the isolated sandbox viewport!',
    iframeFullWidthBtn: 'Open in new window for unrestricted full-screen play',

    // Character Profile Customizer
    customizerHeadline: 'Customize Master Profile',
    lblNickname: 'Venture Nickname',
    lblPersonaTitle: 'Elite Card Title',
    scoreSummary: '🏆 Score MMR: {score} pts',
    scoreSummarySub: 'This rating recalculates your ranking on the worldwide leaderboard live. Try a new name!',
    btnApplyCustomizer: 'Confirm & Enter the Arena!',
    defaultNickname: 'Master Dragon',
    defaultTitle: 'Eastern Sovereign',
    defaultLocalTitle: 'Wanhua Wind Rider',

    // App.tsx Specific Customizer Keys
    custTitle: 'Customize Master Profile',
    custLabelNickname: 'Venture Nickname',
    custPlaceholder: 'Enter nickname...',
    custLabelTitle: 'Elite Card Title',
    custScoreText: 'Score MMR',
    custDescText: 'This rating recalculates your ranking on the worldwide leaderboard live. Try a new name!',
    custConfirmBtn: 'Confirm & Enter the Arena!',

    // Leaderboard
    leaderboardTitle: '🏆 Taiwan Big Two - Real-Time Leaderboard',
    leaderboardDesc: 'Calculated instantly from players nationwide. Crack puzzles or win matches to advance your card reputation!',
    leaderboardLiveBadge: 'Live Synced',
    thRank: 'Rank',
    thName: 'ID Name',
    thTitle: 'Persona Title',
    thRecord: 'Stats Record',
    thPoints: 'Precise MMR Points',
    thMedals: 'Honor Medals',
    winText: 'Wins',
    gameText: 'Matches',
    youLabel: '(You)',

    // App.tsx Specific Leaderboard Keys
    leaderboardStatus: 'Live Synced',
    leaderboardThRank: 'Rank',
    leaderboardThName: 'ID Name',
    leaderboardThTitle: 'Persona Title',
    leaderboardThRecord: 'Stats Record',
    leaderboardThScore: 'Precise MMR Points',
    leaderboardThMedals: 'Honor Medals',

    // Algorithm & Tech
    techTag: 'Open Source Tech: Decision-Tree Card Brains',
    techTitle: 'Powered by `taiwan-big-two-ai` Logic Architecture',
    techDesc: 'The decision-making rules inherit the robust open-source spirit of mesmerli/taiwan-big-two-ai, handling massive search pathways with optimal heuristics.',
    techBullet1: 'Five-card pruning: optimizes straights, flushes, full houses, and four-of-a-kinds to guarantee precise tactical beatings.',
    techBullet2: 'Club 3 custom validation: fully covers traditional rules where holders of Club 3 must open the initial round.',
    techBullet3: 'Four-of-a-kind hijacking exceptions: models exactly the state transitions for heavy high hands taking back initiative.',
    codeSnippetTitle: '📂 @utils/bigTwoRules.ts - Core Decision Skeleton',
    codeSnippetFooter: '🎉 For exhaustive search tree neural network probabilities, grab coordinates on GitHub.',

    // App.tsx Specific Algorithm & Tech Keys
    techBadge: 'Open Source Tech: Decision-Tree Card Brains',
    techLi1: 'Five-card pruning: optimizes straights, flushes, full houses, and four-of-a-kinds to guarantee precise tactical beatings.',
    techLi2: 'Club 3 custom validation: fully covers traditional rules where holders of Club 3 must open the initial round.',
    techLi3: 'Four-of-a-kind hijacking exceptions: models exactly the state transitions for heavy high hands taking back initiative.',
    techFooterNotice: 'For exhaustive search tree neural network probabilities, grab coordinates on GitHub.',

    // Footer
    footerCommunity: 'Taiwan Big Two AI Federation',
    footerCommunityDesc: 'An open-source poker project lovingly crafted of, by, and for fans of Traditional Taiwanese poker.',
    footerContact: 'Contact Email: ',
    footerDlClient: 'Download Windows App:',
    footerCoreProject: 'Core Project Framework:',

    // App.tsx Specific Footer Keys
    footerTitle: 'Taiwan Big Two AI Federation',
    footerDesc: 'An open-source poker project lovingly crafted of, by, and for fans of Traditional Taiwanese poker.',
    footerDownloadText: 'Download Windows App:',
    footerPlatformText: 'Microsoft Store Official Download (30-day Free Trial)',
    footerRepoText: 'Core Project Framework:',
    shareToastText: 'Copied link! Share it with friends to challenge them! 🃏',

    // BigTwoGame.tsx Translations
    gameSoundOn: 'Sound effects: On',
    gameSoundOff: 'Sound effects: Off',
    game1v1Tag: '🤝 1v1 Arena',
    gameTurnMyTurn: '💡 YOUR TURN! Pick a valid combo, click "Play"',
    gameTurnOppTurn: '⏳ Opponent is calculating tactics. Standing by...',
    gameBtnPlay: '🚀 Play カード',
    gameBtnPass: '💨 Pass',
    gameBtnReset: 'Clear',
    gameLogHeader: 'Battlefield Logs',
    gameEmptyLog: 'No logs recorded.',
    gameMyProfile: '💡 Player Panel',
    gameProfileNickname: 'Nickname',
    gameProfileTitle: 'Rank Title',
    gameProfileTip: 'Succeed in matches or challenges to raise points and claim top positions on global leaderboard!',

    gameInitNormalLog: '💡 Duel initiated! [{name}] goes first with [Club 3]!',
    gameSpeechAiMaster: 'Haha! The vital Club 3 is in my custody. I set the momentum!',
    gameSpeechHumanMaster: 'Behold the winning combination! Prepare for defeat!',
    gamePuzzleStartLog: '⚔️ [Puzzle Active]: {title}',
    gamePuzzleStartOppLabel: '📢 Fight matchup: {desc}',
    gamePuzzleStartInfoLine: '💡 Put down cards calculatedly. Defeat the puzzle gatekeeper within the turn limit!',
    gamePuzzleStartHumanSpeech: 'Puzzle layout fixed! Watch me solve this gracefully!',
    gameSpeechSingleCard: 'Heads up! Only 1 card left in hand! Listening!',
    gameLogPlayed: '🥊 [{name}] played: [{type}] ({cardsDesc})',
    gameLogPassed: '💨 [{name}] chose to [Pass].',
    gameLogCleared: '🔄 All passed. Table cleared! [{name}] wins the lead!',
    gameResultTitleWin: '🏆 Challenge Solved!',
    gameResultBodyWin: '🎉 Genius! You cracked this Daily Puzzle! High scores added to profile.',
    gameResultTitleLose: '💀 Challenge Failed',
    gameResultBodyLose: '❌ Hard luck! Opponent defensive blocks worked fine. Try a different strategy!',
    gamePlayAgain: 'Play Again',
    gameResetSetup: 'Reset Setup',
    gameReturnNormalMode: 'Standard Mode',
    gameTitleWinNormal: '🏆 Victory! [{name}] successfully cleared all cards and won! 👑',
    gameTitleLoseNormal: '💀 Defeat! [{name}] dominated the board. Train more on puzzles!',

    // Titles
    localTitles: [
      'Ximending Angler',
      'Xinyi Handsome',
      'Wanhua Wind Rider',
      'Daan Landlord',
      'Tamsui river Wizard',
      'Fengchia Belle',
      'Fa-Ge of Kaohsiung',
      'Old Pi of Sanchong',
      'Bobaprincess Lover',
      'Overtime Techie'
    ],
    opponent1Name: 'Eastern Sovereign',
    opponent2Name: 'Fa-Ge of Kaohsiung',
    opponent3Name: 'Old Pi of Sanchong',
    opponentMysticName: 'Mystic Master',
    oppTitle1: 'Elite Sovereign',
    oppTitle2: 'Night Market Legend',
    oppTitle3: 'Solver of Wanhua',
    generalOpponentTag: 'Puzzle Contender',
    generalExaminerTag: 'Puzzle Overseer',

    // Character profiles keys
    charSectionTitle: 'AI Character Profiles',
    charSectionSubtitle: 'Understand the distinct personality, leading patterns, and tactical logic of each AI player!',
    charTypeHeuristic: 'Heuristic-Driven AIs',
    charTypeLlm: 'LLM-Powered Expert AIs',
    charEngineTitle: '🔄 LLM Characters Dynamic Persona Engine',
    charEngineDesc: 'LLM characters randomly adapt one unique playstyle dynamic before each match starts:',
    charEngine1Title: 'The Wall',
    charEngine1Desc: 'Defense-first. Splits own combinations or high cards to firmly block opponents about to win.',
    charEngine2Title: 'The Sprinter',
    charEngine2Desc: 'Absolute speed. Plays major 5-card combos & high pairs earlier to clear hand fastest.',
    charEngine3Title: 'The Predator',
    charEngine3Desc: 'Hides strength. Passes early to save powerful singles and high pairs for late-game domination.',
    charEngine4Title: 'The Berserker (Ares Only)',
    charEngine4Desc: 'Dislikes passing. Forces moves whenever possible and plays biggest cards to sustain control.',
    charAlexTitle: 'Alex — Balanced Strategy',
    charAlexDesc: 'A versatile general who dynamically adjusts pacing according to opponent threats.',
    charAlexLead: 'Lead Pref / Card Priority: In defense, avoids pairs (5-cards ➔ Non-2 singles ➔ Minor single). In normal, 5-cards ➔ Pairs ➔ Singles.',
    charBellaTitle: 'Bella — Defensive pairs',
    charBellaDesc: 'A conservative defender relying on Pairs to slow down matches, saving high singles for protection.',
    charBellaLead: 'Lead Pref / Card Priority: Always leads smallest pairs first. Lacking pairs, plays 5-cards. Plays minor single as a last resort.',
    charChrisTitle: 'Chris — Aggressive High',
    charChrisDesc: 'A hyper-offensive racer. Intends to crush counters early with massive cards to keep priority.',
    charChrisLead: 'Lead Pref / Card Priority: Leads largest 5-card combo. Lacking combos, blasts largest non-2 single to seize tempo, with 2 for backup.',
    charDianaTitle: 'Diana — The Oracle',
    charDianaDesc: 'Excellent at combo pathways. Builds synergistic hands and utilizes J, Q, K as strategic bridges.',
    charDianaTactics: 'Core Tactics: Actively constructs sequences (Straights, Pairs) to control intermediate game states.',
    charAresTitle: 'Ares — The God of War',
    charAresDesc: 'Supreme high-card controller. Disrupts opponent hand structure with mid-tier 7, 8, 9 cards.',
    charAresTactics: 'Core Tactics: Treats Aces and 2s as ultimate tactical leverage. Withholds them until opponents deplete resources.',
  }
} as const;
